// Writes .env.local for the native local stack with freshly generated local-only
// secrets. Values here only work against your own local Postgres and Auth binary.
import { createHmac, randomBytes } from 'node:crypto';
import { existsSync, writeFileSync } from 'node:fs';
import path from 'node:path';

const root = path.resolve(import.meta.dirname, '../..');
const target = path.join(root, '.env.local');
if (existsSync(target) && !process.argv.includes('--force')) {
  console.log('.env.local already exists; pass --force to regenerate');
  process.exit(0);
}

const secret = randomBytes(32).toString('base64url');
const b64 = (value) => Buffer.from(JSON.stringify(value)).toString('base64url');
function sign(role) {
  const header = b64({ alg: 'HS256', typ: 'JWT' });
  const payload = b64({ iss: 'supabase-local', role, iat: 1700000000, exp: 4102444800 });
  const signature = createHmac('sha256', secret).update(`${header}.${payload}`).digest('base64url');
  return `${header}.${payload}.${signature}`;
}

const lines = [
  '# Generated by scripts/local/write-env.mjs for the native local stack. Do not commit.',
  'APP_MODE=development',
  'APP_URL=http://localhost:3000',
  'NEXT_TELEMETRY_DISABLED=1',
  'SUPABASE_URL=http://127.0.0.1:54321',
  `SUPABASE_ANON_KEY=${sign('anon')}`,
  `SUPABASE_SERVICE_ROLE_KEY=${sign('service_role')}`,
  `LOCAL_JWT_SECRET=${secret}`,
  'DATABASE_URL=postgres://postgres@127.0.0.1:54322/ten',
  'BACKEND_URL=http://127.0.0.1:8000',
  'BACKEND_SERVICE_SECRET=',
  '',
];
writeFileSync(target, lines.join('\n'), { mode: 0o600 });
console.log('Wrote .env.local');
