"""initial schema

Autogenerated against pgserver (Postgres 16.2, pgvector 0.6.2) and hand-checked: creates the
`vector` extension first, reads the embedding dimension from settings, and carries the GIN
index on the generated `search_tsv` column, the HNSW cosine indexes and every CHECK constraint.

Revision ID: 0001
Revises: 
Create Date: 2026-09-28 15:11:38.852908+00:00

"""
# ruff: noqa: E501
from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from pgvector.sqlalchemy import Vector
from sqlalchemy.dialects import postgresql

from app.config import get_settings

# The vector column dimension is read from configuration at migration time; changing provider
# to a different dimension is a new migration and a re-embed of the library.
EMBEDDING_DIM = get_settings().embedding_dimension

# revision identifiers, used by Alembic.
revision: str = '0001'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organisations',
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('topic_taxonomy', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('events',
    sa.Column('entity_type', sa.String(length=32), nullable=False),
    sa.Column('entity_id', sa.UUID(), nullable=False),
    sa.Column('event_type', sa.String(length=32), nullable=False),
    sa.Column('actor', sa.String(length=200), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("entity_type IN ('question', 'answer', 'document', 'tender', 'fact', 'job', 'thread', 'supersession_decision', 'knowledge_item')", name='ck_events_entity_type'),
    sa.CheckConstraint("event_type IN ('status_changed', 'assigned', 'answer_created', 'answer_saved_from_chat', 'verbatim_accepted', 'comment_added', 'document_superseded', 'supersession_decided', 'pair_fixed', 'fact_superseded', 'fact_expired', 'answer_needs_review', 'attested', 'disputed', 'gap_acknowledged', 'compliance_class_set', 'evidence_added', 'job_failed', 'answer_promoted')", name='ck_events_event_type'),
    sa.ForeignKeyConstraint(['org_id'], ['organisations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_events_entity', 'events', ['entity_type', 'entity_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_events_org_id'), 'events', ['org_id'], unique=False)
    op.create_table('jobs',
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=16), server_default=sa.text("'queued'"), nullable=False),
    sa.Column('attempts', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('total', sa.Integer(), nullable=True),
    sa.Column('done', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('results', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('next_job_id', sa.UUID(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("kind IN ('ingest_document', 'extract_questions', 'triage_tender', 'draft_all')", name='ck_jobs_kind'),
    sa.CheckConstraint("status IN ('queued', 'running', 'done', 'failed')", name='ck_jobs_status'),
    sa.ForeignKeyConstraint(['next_job_id'], ['jobs.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['org_id'], ['organisations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_jobs_org_id'), 'jobs', ['org_id'], unique=False)
    op.create_index('ix_jobs_status_created', 'jobs', ['status', 'created_at'], unique=False)
    op.create_table('tenders',
    sa.Column('name', sa.String(length=512), nullable=False),
    sa.Column('buyer', sa.String(length=256), nullable=True),
    sa.Column('deadline', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=16), server_default=sa.text("'open'"), nullable=False),
    sa.Column('outcome', sa.String(length=16), server_default=sa.text("'pending'"), nullable=False),
    sa.Column('outcome_notes', sa.Text(), nullable=True),
    sa.Column('regime', sa.String(length=32), nullable=True),
    sa.Column('is_framework', sa.Boolean(), nullable=True),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('extract_job_id', sa.UUID(), nullable=True),
    sa.Column('triage_job_id', sa.UUID(), nullable=True),
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("outcome IN ('pending', 'won', 'lost', 'unknown')", name='ck_tenders_outcome'),
    sa.CheckConstraint("regime IN ('procurement_act', 'psr', 'pcr_2015', 'other')", name='ck_tenders_regime'),
    sa.CheckConstraint("status IN ('open', 'submitted', 'archived')", name='ck_tenders_status'),
    sa.ForeignKeyConstraint(['extract_job_id'], ['jobs.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['org_id'], ['organisations.id'], ),
    sa.ForeignKeyConstraint(['triage_job_id'], ['jobs.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tenders_org_id'), 'tenders', ['org_id'], unique=False)
    op.create_table('documents',
    sa.Column('filename', sa.String(length=512), nullable=False),
    sa.Column('storage_path', sa.String(length=1024), nullable=False),
    sa.Column('doc_type', sa.String(length=32), nullable=True),
    sa.Column('doc_kind', sa.String(length=64), nullable=True),
    sa.Column('tender_id', sa.UUID(), nullable=True),
    sa.Column('tender_doc_kind', sa.String(length=32), nullable=True),
    sa.Column('effective_date', sa.Date(), nullable=True),
    sa.Column('effective_date_source', sa.String(length=16), nullable=True),
    sa.Column('classification_confirmed', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('superseded_by', sa.UUID(), nullable=True),
    sa.Column('buyer', sa.String(length=256), nullable=True),
    sa.Column('submission_date', sa.Date(), nullable=True),
    sa.Column('outcome', sa.String(length=16), nullable=True),
    sa.Column('ingest_status', sa.String(length=16), server_default=sa.text("'queued'"), nullable=False),
    sa.Column('ingest_error', sa.Text(), nullable=True),
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("doc_kind IN ('dspt_confirmation', 'cyber_essentials_plus', 'iso_27001', 'clinical_safety_case', 'information_security_policy', 'product_description', 'other')", name='ck_documents_doc_kind'),
    sa.CheckConstraint("doc_type IN ('past_submission', 'reference', 'tender_document')", name='ck_documents_doc_type'),
    sa.CheckConstraint("effective_date_source IN ('extracted', 'upload_time', 'user')", name='ck_documents_effective_date_source'),
    sa.CheckConstraint("ingest_status IN ('queued', 'parsing', 'classifying', 'extracting', 'embedding', 'linking', 'ready', 'failed')", name='ck_documents_ingest_status'),
    sa.CheckConstraint("outcome IN ('won', 'lost', 'unknown')", name='ck_documents_outcome'),
    sa.CheckConstraint("tender_doc_kind IN ('question_pack', 'specification', 'clarification_log', 'contract_terms', 'other')", name='ck_documents_tender_doc_kind'),
    sa.ForeignKeyConstraint(['org_id'], ['organisations.id'], ),
    sa.ForeignKeyConstraint(['superseded_by'], ['documents.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tender_id'], ['tenders.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_documents_org_id'), 'documents', ['org_id'], unique=False)
    op.create_index('ix_documents_org_tender', 'documents', ['org_id', 'tender_id'], unique=False)
    op.create_index(op.f('ix_documents_tender_id'), 'documents', ['tender_id'], unique=False)
    op.create_table('document_sections',
    sa.Column('document_id', sa.UUID(), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('heading_path', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('page_start', sa.Integer(), nullable=True),
    sa.Column('page_end', sa.Integer(), nullable=True),
    sa.Column('table_index', sa.Integer(), nullable=True),
    sa.Column('cell_ref', sa.String(length=64), nullable=True),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['org_id'], ['organisations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('document_id', 'order_index', name='uq_document_sections_order')
    )
    op.create_index(op.f('ix_document_sections_document_id'), 'document_sections', ['document_id'], unique=False)
    op.create_index(op.f('ix_document_sections_org_id'), 'document_sections', ['org_id'], unique=False)
    op.create_table('questions',
    sa.Column('tender_id', sa.UUID(), nullable=False),
    sa.Column('document_id', sa.UUID(), nullable=False),
    sa.Column('section', sa.String(length=256), nullable=False),
    sa.Column('number', sa.String(length=64), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('word_limit', sa.Integer(), nullable=True),
    sa.Column('weighting', sa.Float(), nullable=True),
    sa.Column('response_type', sa.String(length=16), server_default=sa.text("'free_text'"), nullable=False),
    sa.Column('mandatory', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('topics', postgresql.ARRAY(sa.String(length=64)), server_default=sa.text("'{}'::varchar[]"), nullable=False),
    sa.Column('embedding', Vector(EMBEDDING_DIM), nullable=True),
    sa.Column('coverage', sa.String(length=16), server_default=sa.text("'unknown'"), nullable=False),
    sa.Column('coverage_detail', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('compliance_class', sa.String(length=1), nullable=True),
    sa.Column('compliant_by', sa.Date(), nullable=True),
    sa.Column('assignee', sa.String(length=200), nullable=True),
    sa.Column('status', sa.String(length=16), server_default=sa.text("'not_started'"), nullable=False),
    sa.Column('needs_review', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('gap_acknowledgements', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("compliance_class IN ('A', 'B', 'C')", name='ck_questions_compliance_class'),
    sa.CheckConstraint("coverage IN ('covered', 'partial', 'new', 'unknown')", name='ck_questions_coverage'),
    sa.CheckConstraint("response_type IN ('free_text', 'yes_no', 'attachment', 'table', 'pricing', 'other')", name='ck_questions_response_type'),
    sa.CheckConstraint("status IN ('not_started', 'ai_draft', 'writer_edited', 'sme_verified', 'approved')", name='ck_questions_status'),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['org_id'], ['organisations.id'], ),
    sa.ForeignKeyConstraint(['tender_id'], ['tenders.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tender_id', 'section', 'number', name='uq_questions_tender_number')
    )
    op.create_index(op.f('ix_questions_org_id'), 'questions', ['org_id'], unique=False)
    op.create_index('ix_questions_tender_order', 'questions', ['tender_id', 'order_index'], unique=False)
    op.create_table('supersession_decisions',
    sa.Column('doc_kind', sa.String(length=64), nullable=False),
    sa.Column('document_a_id', sa.UUID(), nullable=False),
    sa.Column('document_b_id', sa.UUID(), nullable=False),
    sa.Column('reason', sa.String(length=16), nullable=False),
    sa.Column('decision', sa.String(length=16), server_default=sa.text("'pending'"), nullable=False),
    sa.Column('superseding_document_id', sa.UUID(), nullable=True),
    sa.Column('decided_by', sa.String(length=200), nullable=True),
    sa.Column('decided_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("decision IN ('pending', 'superseded', 'keep_both')", name='ck_supersession_decisions_decision'),
    sa.CheckConstraint("doc_kind IN ('dspt_confirmation', 'cyber_essentials_plus', 'iso_27001', 'clinical_safety_case', 'information_security_policy', 'product_description', 'other')", name='ck_supersession_decisions_doc_kind'),
    sa.CheckConstraint("reason IN ('auto', 'pending_date', 'tie', 'keyed_kind')", name='ck_supersession_decisions_reason'),
    sa.CheckConstraint('document_a_id < document_b_id', name='ck_supersession_pair_ordered'),
    sa.ForeignKeyConstraint(['document_a_id'], ['documents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['document_b_id'], ['documents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['org_id'], ['organisations.id'], ),
    sa.ForeignKeyConstraint(['superseding_document_id'], ['documents.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('document_a_id', 'document_b_id', name='uq_supersession_pair')
    )
    op.create_index(op.f('ix_supersession_decisions_org_id'), 'supersession_decisions', ['org_id'], unique=False)
    op.create_table('comments',
    sa.Column('question_id', sa.UUID(), nullable=False),
    sa.Column('author', sa.String(length=200), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organisations.id'], ),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_comments_org_id'), 'comments', ['org_id'], unique=False)
    op.create_index(op.f('ix_comments_question_id'), 'comments', ['question_id'], unique=False)
    op.create_table('knowledge_items',
    sa.Column('document_id', sa.UUID(), nullable=False),
    sa.Column('section_id', sa.UUID(), nullable=False),
    sa.Column('answer_start', sa.Integer(), nullable=False),
    sa.Column('answer_end', sa.Integer(), nullable=False),
    sa.Column('question_section_id', sa.UUID(), nullable=True),
    sa.Column('question_start', sa.Integer(), nullable=True),
    sa.Column('question_end', sa.Integer(), nullable=True),
    sa.Column('item_type', sa.String(length=32), nullable=False),
    sa.Column('question_text', sa.Text(), nullable=True),
    sa.Column('answer_text', sa.Text(), nullable=False),
    sa.Column('text_verified', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('topics', postgresql.ARRAY(sa.String(length=64)), server_default=sa.text("'{}'::varchar[]"), nullable=False),
    sa.Column('canonical_id', sa.UUID(), nullable=True),
    sa.Column('is_canonical', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('question_embedding', Vector(EMBEDDING_DIM), nullable=True),
    sa.Column('answer_embedding', Vector(EMBEDDING_DIM), nullable=True),
    sa.Column('search_tsv', postgresql.TSVECTOR(), sa.Computed("setweight(to_tsvector('english', coalesce(question_text, '')), 'A') || setweight(to_tsvector('english', answer_text), 'B')", persisted=True), nullable=False),
    sa.Column('excluded_from_retrieval', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("item_type IN ('qa_pair', 'chunk', 'promoted_answer')", name='ck_knowledge_items_item_type'),
    sa.ForeignKeyConstraint(['canonical_id'], ['knowledge_items.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['org_id'], ['organisations.id'], ),
    sa.ForeignKeyConstraint(['question_section_id'], ['document_sections.id'], ),
    sa.ForeignKeyConstraint(['section_id'], ['document_sections.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_knowledge_items_answer_embedding', 'knowledge_items', ['answer_embedding'], unique=False, postgresql_using='hnsw', postgresql_with={'m': 16, 'ef_construction': 64}, postgresql_ops={'answer_embedding': 'vector_cosine_ops'})
    op.create_index(op.f('ix_knowledge_items_canonical_id'), 'knowledge_items', ['canonical_id'], unique=False)
    op.create_index(op.f('ix_knowledge_items_document_id'), 'knowledge_items', ['document_id'], unique=False)
    op.create_index('ix_knowledge_items_eligibility', 'knowledge_items', ['org_id', 'excluded_from_retrieval', 'text_verified'], unique=False)
    op.create_index(op.f('ix_knowledge_items_org_id'), 'knowledge_items', ['org_id'], unique=False)
    op.create_index('ix_knowledge_items_question_embedding', 'knowledge_items', ['question_embedding'], unique=False, postgresql_using='hnsw', postgresql_with={'m': 16, 'ef_construction': 64}, postgresql_ops={'question_embedding': 'vector_cosine_ops'})
    op.create_index('ix_knowledge_items_search_tsv', 'knowledge_items', ['search_tsv'], unique=False, postgresql_using='gin')
    op.create_index(op.f('ix_knowledge_items_section_id'), 'knowledge_items', ['section_id'], unique=False)
    op.create_table('question_evidence',
    sa.Column('question_id', sa.UUID(), nullable=False),
    sa.Column('document_id', sa.UUID(), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['org_id'], ['organisations.id'], ),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('question_id', 'document_id', name='uq_question_evidence_document')
    )
    op.create_index(op.f('ix_question_evidence_org_id'), 'question_evidence', ['org_id'], unique=False)
    op.create_table('threads',
    sa.Column('tender_id', sa.UUID(), nullable=False),
    sa.Column('question_id', sa.UUID(), nullable=True),
    sa.Column('title', sa.String(length=512), nullable=False),
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organisations.id'], ),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tender_id'], ['tenders.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('question_id', name='uq_threads_question')
    )
    op.create_index(op.f('ix_threads_org_id'), 'threads', ['org_id'], unique=False)
    op.create_table('answers',
    sa.Column('question_id', sa.UUID(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('author_type', sa.String(length=8), nullable=False),
    sa.Column('author_name', sa.String(length=200), nullable=True),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('word_count', sa.Integer(), nullable=False),
    sa.Column('segments', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('gaps', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('fact_checklist', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('verbatim_offer_item_id', sa.UUID(), nullable=True),
    sa.Column('verbatim_source_item_id', sa.UUID(), nullable=True),
    sa.Column('support_summary', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('model', sa.String(length=128), nullable=True),
    sa.Column('prompt_version', sa.String(length=128), nullable=True),
    sa.Column('is_current', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("author_type IN ('ai', 'user')", name='ck_answers_author_type'),
    sa.ForeignKeyConstraint(['org_id'], ['organisations.id'], ),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['verbatim_offer_item_id'], ['knowledge_items.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['verbatim_source_item_id'], ['knowledge_items.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('question_id', 'version', name='uq_answers_question_version')
    )
    op.create_index(op.f('ix_answers_org_id'), 'answers', ['org_id'], unique=False)
    op.create_index('uq_answers_one_current', 'answers', ['question_id'], unique=True, postgresql_where=sa.text('is_current'))
    op.create_table('facts',
    sa.Column('document_id', sa.UUID(), nullable=False),
    sa.Column('section_id', sa.UUID(), nullable=False),
    sa.Column('knowledge_item_id', sa.UUID(), nullable=True),
    sa.Column('fact_kind', sa.String(length=64), nullable=False),
    sa.Column('fact_key', sa.String(length=256), nullable=True),
    sa.Column('statement', sa.Text(), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.Column('effective_date', sa.Date(), nullable=False),
    sa.Column('expires_on', sa.Date(), nullable=True),
    sa.Column('expired_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('superseded_by', sa.UUID(), nullable=True),
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("fact_kind IN ('dspt_status', 'cyber_essentials_plus', 'iso_27001', 'clinical_safety_case', 'clinical_safety_officer', 'mhra_registration', 'data_protection_officer', 'insurance_cover', 'headcount', 'company_registration', 'accreditation_other')", name='ck_facts_fact_kind'),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['knowledge_item_id'], ['knowledge_items.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['org_id'], ['organisations.id'], ),
    sa.ForeignKeyConstraint(['section_id'], ['document_sections.id'], ),
    sa.ForeignKeyConstraint(['superseded_by'], ['facts.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_facts_document_id'), 'facts', ['document_id'], unique=False)
    op.create_index('ix_facts_kind_key', 'facts', ['org_id', 'fact_kind', 'fact_key'], unique=False)
    op.create_index(op.f('ix_facts_knowledge_item_id'), 'facts', ['knowledge_item_id'], unique=False)
    op.create_index(op.f('ix_facts_org_id'), 'facts', ['org_id'], unique=False)
    op.create_table('unpaired_fragments',
    sa.Column('document_id', sa.UUID(), nullable=False),
    sa.Column('section_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.String(length=16), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('start', sa.Integer(), nullable=True),
    sa.Column('end', sa.Integer(), nullable=True),
    sa.Column('resolved_item_id', sa.UUID(), nullable=True),
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("role IN ('question', 'answer', 'unknown')", name='ck_unpaired_fragments_role'),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['org_id'], ['organisations.id'], ),
    sa.ForeignKeyConstraint(['resolved_item_id'], ['knowledge_items.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['section_id'], ['document_sections.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_unpaired_fragments_document_id'), 'unpaired_fragments', ['document_id'], unique=False)
    op.create_index(op.f('ix_unpaired_fragments_org_id'), 'unpaired_fragments', ['org_id'], unique=False)
    op.create_table('messages',
    sa.Column('thread_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.String(length=16), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('segments', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('rewritten_query', sa.Text(), nullable=True),
    sa.Column('retrieved_item_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('support_summary', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('gaps', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('fact_checklist', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('verbatim_offer_item_id', sa.UUID(), nullable=True),
    sa.Column('model', sa.String(length=128), nullable=True),
    sa.Column('prompt_version', sa.String(length=128), nullable=True),
    sa.Column('answer_id', sa.UUID(), nullable=True),
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("role IN ('user', 'assistant', 'system')", name='ck_messages_role'),
    sa.ForeignKeyConstraint(['answer_id'], ['answers.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['org_id'], ['organisations.id'], ),
    sa.ForeignKeyConstraint(['thread_id'], ['threads.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['verbatim_offer_item_id'], ['knowledge_items.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_messages_org_id'), 'messages', ['org_id'], unique=False)
    op.create_index('ix_messages_thread_created', 'messages', ['thread_id', 'created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # The vector extension is left in place: dropping it is a deployment decision.
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_messages_thread_created', table_name='messages')
    op.drop_index(op.f('ix_messages_org_id'), table_name='messages')
    op.drop_table('messages')
    op.drop_index(op.f('ix_unpaired_fragments_org_id'), table_name='unpaired_fragments')
    op.drop_index(op.f('ix_unpaired_fragments_document_id'), table_name='unpaired_fragments')
    op.drop_table('unpaired_fragments')
    op.drop_index(op.f('ix_facts_org_id'), table_name='facts')
    op.drop_index(op.f('ix_facts_knowledge_item_id'), table_name='facts')
    op.drop_index('ix_facts_kind_key', table_name='facts')
    op.drop_index(op.f('ix_facts_document_id'), table_name='facts')
    op.drop_table('facts')
    op.drop_index('uq_answers_one_current', table_name='answers', postgresql_where=sa.text('is_current'))
    op.drop_index(op.f('ix_answers_org_id'), table_name='answers')
    op.drop_table('answers')
    op.drop_index(op.f('ix_threads_org_id'), table_name='threads')
    op.drop_table('threads')
    op.drop_index(op.f('ix_question_evidence_org_id'), table_name='question_evidence')
    op.drop_table('question_evidence')
    op.drop_index(op.f('ix_knowledge_items_section_id'), table_name='knowledge_items')
    op.drop_index('ix_knowledge_items_search_tsv', table_name='knowledge_items', postgresql_using='gin')
    op.drop_index('ix_knowledge_items_question_embedding', table_name='knowledge_items', postgresql_using='hnsw', postgresql_with={'m': 16, 'ef_construction': 64}, postgresql_ops={'question_embedding': 'vector_cosine_ops'})
    op.drop_index(op.f('ix_knowledge_items_org_id'), table_name='knowledge_items')
    op.drop_index('ix_knowledge_items_eligibility', table_name='knowledge_items')
    op.drop_index(op.f('ix_knowledge_items_document_id'), table_name='knowledge_items')
    op.drop_index(op.f('ix_knowledge_items_canonical_id'), table_name='knowledge_items')
    op.drop_index('ix_knowledge_items_answer_embedding', table_name='knowledge_items', postgresql_using='hnsw', postgresql_with={'m': 16, 'ef_construction': 64}, postgresql_ops={'answer_embedding': 'vector_cosine_ops'})
    op.drop_table('knowledge_items')
    op.drop_index(op.f('ix_comments_question_id'), table_name='comments')
    op.drop_index(op.f('ix_comments_org_id'), table_name='comments')
    op.drop_table('comments')
    op.drop_index(op.f('ix_supersession_decisions_org_id'), table_name='supersession_decisions')
    op.drop_table('supersession_decisions')
    op.drop_index('ix_questions_tender_order', table_name='questions')
    op.drop_index(op.f('ix_questions_org_id'), table_name='questions')
    op.drop_table('questions')
    op.drop_index(op.f('ix_document_sections_org_id'), table_name='document_sections')
    op.drop_index(op.f('ix_document_sections_document_id'), table_name='document_sections')
    op.drop_table('document_sections')
    op.drop_index(op.f('ix_documents_tender_id'), table_name='documents')
    op.drop_index('ix_documents_org_tender', table_name='documents')
    op.drop_index(op.f('ix_documents_org_id'), table_name='documents')
    op.drop_table('documents')
    op.drop_index(op.f('ix_tenders_org_id'), table_name='tenders')
    op.drop_table('tenders')
    op.drop_index('ix_jobs_status_created', table_name='jobs')
    op.drop_index(op.f('ix_jobs_org_id'), table_name='jobs')
    op.drop_table('jobs')
    op.drop_index(op.f('ix_events_org_id'), table_name='events')
    op.drop_index('ix_events_entity', table_name='events')
    op.drop_table('events')
    op.drop_table('organisations')
    # ### end Alembic commands ###
